[package]
name = "slab-allocator"
version = "0.1.0"
edition = "2021"
authors = ["idrisbr52@gmail.com"]

[dependencies]
spin = "0.9"

[lib]
name = "slab_allocator"
path = "src/lib.rs"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
opt-level = 3
